name = "SCS"
uuid = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
version = "2.4.0"
repo = "https://github.com/jump-dev/SCS.jl"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SCS_jll = "f4f2fc5b-1d94-523c-97ea-2ab488bedf4b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
SCS_MKL_jll = "3f2553a9-4106-52be-b7dd-865123654657"

[extensions]
SCSSCS_GPU_jllExt = ["SCS_GPU_jll"]
SCSSCS_MKL_jllExt = ["SCS_MKL_jll"]

[compat]
LinearAlgebra = "1.10.0"
MathOptInterface = "1.20"
OpenBLAS32_jll = "0.3.10"
Pkg = "1"
PrecompileTools = "1"
SCS_GPU_jll = "=300.200.900, =300.200.1000"
SCS_MKL_jll = "=300.200.900, =300.200.1000"
SCS_jll = "=300.200.900, =300.200.1000"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
SCS_MKL_jll = "3f2553a9-4106-52be-b7dd-865123654657"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
