name = "SCS"
uuid = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
repo = "https://github.com/jump-dev/SCS.jl"
version = "2.0.2"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SCS_jll = "f4f2fc5b-1d94-523c-97ea-2ab488bedf4b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extensions]
SCSSCS_GPU_jllExt = ["SCS_GPU_jll"]
SCSSCS_MKL_jllExt = ["SCS_MKL_jll"]

[weakdeps]
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
SCS_MKL_jll = "3f2553a9-4106-52be-b7dd-865123654657"

[compat]
MathOptInterface = "1.20"
Pkg = "<0.0.1, ^1.6"
SCS_GPU_jll = "=3.2.4, =3.2.6, =3.2.7"
SCS_MKL_jll = "=3.2.4, =3.2.6, =3.2.7"
SCS_jll = "=3.2.4, =3.2.6, =3.2.7"
SparseArrays = "<0.0.1, ^1.6"
Test = "<0.0.1, ^1.6"
julia = "1.6"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
SCS_MKL_jll = "3f2553a9-4106-52be-b7dd-865123654657"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
