name = "SCS"
uuid = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
repo = "https://github.com/jump-dev/SCS.jl"
version = "0.7.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
SCS_jll = "f4f2fc5b-1d94-523c-97ea-2ab488bedf4b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BinaryProvider = "0.3, 0.4, 0.5"
MathOptInterface = "0.9.7"
MathProgBase = "~0.5.0, ~0.6, ~0.7"
Requires = "1"
SCS_GPU_jll = "2.1"
SCS_jll = "2.1"
julia = "1"

[extras]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Compat", "Pkg", "DelimitedFiles"]
